### ISSUE TITLE
What about œ (e.g. in "cœur")

### ISSUE THREAD

**Issue by epsitec** [thomasgalliker/Diacritics.NET#1]
Hi Thomas, while looking for a solution to normalize diacritics and other digrams, I came across your implementation. I like the way you separated every language into its own set of rules.

However, I don't feel comfortable using it, since it produces unexpected conversions. Say you feed it with "cœur" in French. You'd expect to get "coeur" as an output, but since you map "œ" to "o" you finally get "cour" instead.

Same thing for German words, where "Grüße" might be more appropriately mapped to "Gruesse" (i.e. map ü &rarr; ue and ß &rarr; ss).

Can you explain why you chose your approach of a one-to-one mapping?

**Comment by thomasgalliker** [comment]
Hi Pierre, you're absolutly right. I wasnt thinking of your example when i was creating this library. Honestly, I copied the mappings ftom some stackoverflow page. I can extend the mapping logic to allow multiple characters to be mapped.

**Comment by epsitec** [comment]
It is a complex topic. I've discovered (thanks to this [StackOverflow question](http://stackoverflow.com/questions/359827/ignoring-accented-letters-in-string-comparison)) that .NET had a comparison function which allows for culture aware comparisons (i.e. comparing "Grüße" to "Grusse" returns `0` &rarr; equal).

```c#
string.Compare(s1, s2, CultureInfo.CurrentCulture, CompareOptions.IgnoreNonSpace);
```

However, even this code is not perfect, as it won't consider "ü" and "ue" to be equivalent.

I should probably have a [better look at ICU](http://userguide.icu-project.org/collation/concepts) if I really need solid culture aware comparison and/or sorting, which is aware of phonebook ordering (different from plain ordering in German), where words starting with "ä" appear between those starting with "ad" and "af").
