### ISSUE TITLE
Add a LICENSE.MD file

### ISSUE THREAD

**Issue by prajaybasu** [thomasgalliker/Diacritics.NET#11]
NuGet license info says Apache 2.0, while README.MD doesn't specify a concrete license (except a non commercial clause - even though Apache 2.0 allows commercial usage).  

A LICENSE.MD or LICENSE.TXT file with a proper license would make this project useful for more people.

**Comment by thomasgalliker** [comment]
From a legal point of view, the project comes with dual license: free for non-commercial use or paid if you commercially use it in one of your products. It‘s a matter of fair use: When you earn money with it, it‘s no more than fair to share this success.

I gonna post a license soon. Thanks for the hint.
