### ISSUE TITLE
ı => i

### ISSUE THREAD

**Issue by okankocyigit** [thomasgalliker/Diacritics.NET#12]

**Comment by thomasgalliker** [comment]
I guess this is a Turkish character? I published it in nuget 1.0.8-pre1, can you please have a look and let me know if it works for you?

https://www.nuget.org/packages/Diacritics/1.0.8-pre1

**Comment by okankocyigit** [comment]
yes, it's working well for nuget 1.0.8-pre1, thanks.

bd03cb7111b4934b4400e83a3c49d11345b5c213
