### ISSUE TITLE
Lower-case Latin variants hide upper diacritics

### ISSUE THREAD

**Issue by anth12** [thomasgalliker/Diacritics.NET#16]
When characters have a lower-case Latin equivalent the diacritic is not correctly removed. 
Take for example the Turkish word "İngiltere" (England), when invoking `RemoveDiacritics` the input is converted to lowercase before `IndexOfAny` is called. At this point the input is transformed to "ingiltere" meaning the `İ` diacritic is not replaced & the original string is returned.

**Comment by thomasgalliker** [comment]
This library works with replacement mappings: Diacritics character í is mapped to i, character Í is mapped to I, and so on. There is no general mechanism that maps between diacritics and non-diactritics characters. Can you report all characters (and their normalized equivalents) please?

**Comment by anth12** [comment]
For Turkish there are 4 I's:
> The lowercase version of `İ` is `i`
> The lowercase version of `I` is `ı`

The mappings to "remove diacritics" would be:
`İ`  -> `I`
`ı` -> `i`

However with the current code, simply adding the mapping wouldn't solve due to the lower case conversion as `İ` would be converted to `i` & therefore not replaced.

**Comment by thomasgalliker** [comment]
Hmm, I'm lost somehow. So, if I add these two mappings, it would not be enough to solve the problem?
`İ` -> `I`
`ı` -> `i`

**Comment by anth12** [comment]
There are mappings for the characters, but the issue lies in [DiacriticsMapper#56](https://github.com/thomasgalliker/Diacritics.NET/blob/master/Diacritics/DiacriticsMapper.cs#L56). 

Say I invoke `DiacriticsMapper.RemoveDiacritics("İngiltere")`, at L56 `input = "İngiltere"` & `source = "ingiltere"` which leads to the original `input` being returned as the `while` checks the lowercase `source` for instances of any diacritic character.

**Comment by thomasgalliker** [comment]
Ups, I somehow forgot to come back to this issue. Do you have a proposal on how to solve it? Is it because line 56 does only compare index positions ignoring case sensitivity?

**Comment by thomasgalliker** [comment]
@anth12  can you please check this nuget pre-release:
https://www.nuget.org/packages/Diacritics/2.1.19240.1-pre

**Comment by thomasgalliker** [comment]
Seems like you have your own diacritics library now 🤩 I guess I can close this issue then.
