### ISSUE TITLE
Spanish character missing (ü => u)

### ISSUE THREAD

**Issue by ernestoyaquello** [thomasgalliker/Diacritics.NET#19]
The character `ü` is valid in the Spanish language (e.g., `penguin` is `pingüino` in Spanish).

**Comment by thomasgalliker** [comment]
Yes, thanks for reporting. I added this mapping and it is now part of pull request #20 which will be released as a pre-release nuget in a few minutes.

**Comment by thomasgalliker** [comment]
@ernestoyaquello  your proposal is part of following nuget package:
https://www.nuget.org/packages/Diacritics/2.0.19240.3

Let me know if everything is fine.
