### ISSUE TITLE
FrenchAccentsMapping œ should transform on oe not o

### ISSUE THREAD

**Issue by SteeveDess** [thomasgalliker/Diacritics.NET#26]
Hi,

In French, we have some special word like "œuf" (Egg). For them, after RemoveDiacritics, we should have "oeuf" and not "ouf".
I tracked down the mapping the the file FrenchAccentsMapping. Line 22, the { 'œ', "o" }, should be replaced by { 'œ', "oe" },

Is that possible to do it ?
To make it simple, I submitted a pull request.
Regards
Steeve

**Comment by thomasgalliker** [comment]
Thanks @SteeveDess. I’ll have a look at the PR.

**Comment by thomasgalliker** [comment]
Merged! There is a pre-release nuget on nuget.org. Can you check if you're change is working as you expect: https://www.nuget.org/packages/Diacritics/2.1.20017.2-pre

**Comment by SteeveDess** [comment]
Hi, Yes, I can check.

**Comment by SteeveDess** [comment]
It's working as expected, thank you.
