### ISSUE TITLE
ơ => o

### ISSUE THREAD

**Issue by confiktura** [thomasgalliker/Diacritics.NET#29]
Hi.

Could you please add this mapping for Vietnamese "ơ" letter?

Thanks.

**Comment by confiktura** [comment]
Update: 
This letter has more variations, those should be added as well:
Ờ ờ
Ớ ớ
Ở ở
Ỡ ỡ
Ợ ợ

**Comment by thomasgalliker** [comment]
So, each of these characters is mapping either to an uppercase "O" or lowercase "o"? I can add them to the list. I'll let you know when the nuget is ready for testing.

**Comment by confiktura** [comment]
That's correct, each of them maps to either an uppercase "O" or a lowercase "o". Thank you.

**Comment by thomasgalliker** [comment]
Can you please install the pre-release nuget https://www.nuget.org/packages/Diacritics/2.1.20116.2-pre and let me know if it fits your needs?

**Comment by thomasgalliker** [comment]
@confiktura can you please check the following unit test and let me know, if the diacritics removal in vietnamese language is done correctly: https://github.com/thomasgalliker/Diacritics.NET/blob/5c6b3c6c967f3ea3ec666517001880553cfc5430/Tests/Diacritics.Tests/AccentMappings/VietnameseAccentsMappingTests.cs#L28

**Comment by confiktura** [comment]
Thanks. I will do it some time this week and let you know.

**Comment by confiktura** [comment]
Hi. I've tried the specified nuget package version in a simple console app as such:
```
var str = "Cà phê sữa đá hay còn gọi đơn giản là cà phê sữa là một loại thức uống thông dụng ở Việt Nam.";
var withoutDiacritics = str.RemoveDiacritics();
Console.WriteLine(withoutDiacritics );
Console.ReadKey();
```
The output to the console was `Ca phe s?a da hay con g?i don gi?n la ca phe s?a la m?t lo?i th?c u?ng thong d?ng o Vi?t Nam.`
The value when inspecting the `withoutDiacritics` variable was `Ca phe sữa da hay con gọi dơn giản la ca phe sữa la một loại thức uống thong dụng o Việt Nam.`
The value in the console is probably malformed because of rendering, however the value of `withoutDiacritics` is still with some diacritics. So, atleast some of them were removed, however not all of them. 
Furthermore, I looked at the unit test you linked, the output shouldn't include the character `đ`, instead it should be `d`. Apart from that it looks good.
Please let me know if you can replicate the same behavior. Thanks.

**Comment by thomasgalliker** [comment]
The problem with the question mark sounds like an encoding problem. This might help: `Console.OutputEncoding = System.Text.Encoding.Unicode;`

**Comment by confiktura** [comment]
Yes, this solved the ouput in the console, it's now `Ca phe sữa da hay con gọi dơn giản la ca phe sữa la một loại thức uống thong dụng o Việt Nam.`. However, as you can see, there are still some Diacritics left.

**Comment by thomasgalliker** [comment]
What if you use the very latest prerelease (https://www.nuget.org/packages/Diacritics/3.0.20116.1-pre)?
I pushed two nugets that day... one with only your mentioned characters and one with „all“ vietnamese diacritics. Can you check out 3.0.20116.1-pre? This one should be complete.

**Comment by confiktura** [comment]
With the [https://www.nuget.org/packages/Diacritics/3.0.20116.1-pre](https://www.nuget.org/packages/Diacritics/3.0.20116.1-pre) it's all good. Thank you, I'm closing the issue.
