### ISSUE TITLE
Release Note Availability

### ISSUE THREAD

**Issue by tparikka** [thomasgalliker/Diacritics.NET#49]
Thank you for your work on this project! My team is working a project that utilizes your library and is looking at updating from 2.0.19240.3 to 3.3.18. Do you have release notes available anywhere that we could review for possible breaking changes? I didn't see any release information available in GitHub that I could read through.

**Comment by thomasgalliker** [comment]
Thank you, @tparikka.
It's safe to update as all these updates mainly focus on new diacritics mappings and performance improvements.
Sometimes I note important changes here: https://www.nuget.org/packages/Diacritics#release-body-tab

But, yeah, you're right, it would be awesome to have release notes in this repository.

Hope this helps.

**Comment by tparikka** [comment]
Thank you! Yes, releases in the repository would be much appreciated in the future if it's feasible. It helps my company keep dependencies up to date generally if we can point to a release notes list and indicate what breaking changes we may need to test for. This response will certainly help. Have a great day!
