### ISSUE TITLE
ç => c

### ISSUE THREAD

**Issue by leye0** [thomasgalliker/Diacritics.NET#5]

**Comment by thomasgalliker** [comment]
Hi leye0.
What do you mean by "ç => c"? The cedilla or cédille "ç" is mapped to "c" in the `FrenchAccentsMapping` which is part of the `DefaultDiacriticsMapper`.

**Comment by leye0** [comment]
Oops, I forgot to update the bug, sorry! I finally realized that I came across a ç in a string that was built, for obscure reasons, like so: '̧ + c.  You can see in my example that I'm not even able to separate one of the single quote from the cedille sign. It seems like a lot of software have hack to put together chars to build a single char. I had to do something custom:
    `
        public static string LowerizedNoDiacritics(this string thisString)
        {
            thisString = thisString.RemoveDiacritics().ToLowerInvariant();
            var partialDiacritics = new char[] { '̧' };
            foreach (var c in partialDiacritics)
            {
                thisString = thisString.Replace(c.ToString(), string.Empty);
            }

            return thisString;
        }
`

**Comment by thomasgalliker** [comment]
Ok. Thanks for reporting. I reproduced this issue and solved it in a [pull request](https://github.com/thomasgalliker/Diacritics.NET/pull/6). It's already been merged back to master. Feedback is highly welcome. I gonna release a pre-release of the nuget too, so you can test it in your solution.
